config/routes.rb
Rails.application.routes.draw do
  get 'graphs/show'

  resources :records
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'records#index'

  Rails.application.routes.draw do
    root to: "graphs#show"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :records, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController

  def show
    @records = Record.all
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = current_user.records
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = current_user.records.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = current_user.records.create(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to '/records', notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to '/records', notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:title, :user, :description, :gratitude, :gym, :run, :pressups, :situps, :backpain, :shoulderpain, :blog)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/graphs/show.html.erb
<h1>Graphs</h1>


<!-- <%= area_chart Record.pluck(:run, :backpain).count %> -->

<%= line_chart Record.group(:shoulderpain).group_by_day(:created_at).count %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daily2</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->

  </head>

  <body>

    <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <p>
  <% end %>
    <%= yield %>


    <!-- <%= line_chart User.group_by_day(:created_at).count %> -->

  </body>
</html>

app/views/records/_editform.html.erb
<%= simple_form_for @record do |f| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="jumbotron">
    <div class="field">
      <!-- <%= f.label :title %> -->
      <%= f.input :title, placeholder: "today e.g. 01/01/17" %>
      <%= f.input :description, placeholder: "summarise the day" %>
      <%= f.input :gratitude, placeholder: "what should you be grateful for today?" %>
      <%= f.input :blog %>
      <%= f.input :gym %>
      <%= f.input :run %>
      <%= f.input :pressups %>
      <%= f.input :situps %>
      <%= f.input :backpain %>
      <%= f.input :shoulderpain %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/records/_form.html.erb
<%= form_for(record) do |f| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'editform', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diary</h1>

<%= link_to image_tag("add.png", :size => "200x200"), new_record_path %>

<%= link_to image_tag("graph.png", :size => "200x200"), graphs_show_path %>



<p>
<table>
  <thead>
    <tr>
      <th>Previous</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <!-- <td><%= record.title %></td>
        <td><%= link_to 'Show', record %></td> -->
        <td><%= link_to record.title, edit_record_path(record) %></td>
        <!-- <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'editform', record: @record %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @record.title %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>